addons:
    chrome: stable
before_install:
    - # start your web application and listen on `localhost`
    - google-chrome-stable --headless --disable-gpu --remote-debugging-port=9222 http://localhost &
language: node_js
node_js:
    - '10'
    - '12'
script:
    - npm run build
    - npm run webserver &
    - npm test
